version: "3.9"

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=123456
      - "MYSQL_ROOT_HOST=%"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - 9999:80
    environment:
      - PMA_HOST=database

  # backend:
  #   container_name: backend
  #   build: ./backend
  #   volumes:
  #     - ./backend:/src
  #     - nodemodules:/src/node_modules
  #   depends_on:
  #     - database
  #   ports:
  #     - 5000:5000

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   volumes:
  #     - /src/app/node_modules
  #     - ./frontend:/src/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
volumes:
  nodemodules: {}
